/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package privacy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EGC
 */
public class CSP extends javax.swing.JFrame {

    /**
     * Creates new form CSP
     */
     Statement st;
    Connection con;
    public CSP() throws ClassNotFoundException, SQLException {
        initComponents();
        
         Class.forName("com.mysql.jdbc.Driver");
       
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"privacy","root","root");
             System.out.println("Connected");
             st=con.createStatement();
             
              String query="select * from access where UID='"+signin.uid+"' ";
             st=con.createStatement();
             ResultSet rs=st.executeQuery(query);
             while(rs.next())
             {
                String ids = rs.getString(1);
                String names = rs.getString(2);
                String fnames = rs.getString(3);

                id.setText(ids);
                name.setText(names);
                fname.setText(fnames);
             }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        oid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sigs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Efficient Privacy-Aware Authentication Scheme for ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 10, 550, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Mobile Cloud Computing Services");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 60, 360, 30);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("User-ID");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(140, 50, 70, 20);
        jPanel4.add(id);
        id.setBounds(240, 40, 140, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("User-Name");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(140, 100, 80, 17);
        jPanel4.add(name);
        name.setBounds(240, 90, 140, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Ragavi\\images\\mobile\\user.png")); // NOI18N
        jLabel8.setText("jLabel3");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 50, 100, 100);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("File Name");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(140, 140, 80, 29);

        fname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel4.add(fname);
        fname.setBounds(240, 140, 140, 23);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(130, 110, 490, 200);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CSP Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Owner-ID");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(140, 50, 70, 20);
        jPanel3.add(oid);
        oid.setBounds(240, 40, 140, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Signature");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(140, 100, 80, 17);
        jPanel3.add(sigs);
        sigs.setBounds(240, 90, 140, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Ragavi\\images\\mobile\\ADMIN.png")); // NOI18N
        jLabel5.setText("jLabel3");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 40, 100, 110);

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setText("SEND KEY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(220, 150, 100, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(130, 350, 540, 200);

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setText("GET KEY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 320, 100, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String qry="select * from files where Filename='"+fname.getText()+"'";
         try {
             st=con.createStatement();
               ResultSet rs=st.executeQuery(qry);
               while(rs.next())
             {
                String ids = rs.getString(1);
                String signature = rs.getString(4);

                oid.setText(ids);
                sigs.setText(signature);
               
             }
         } catch (SQLException ex) {
             Logger.getLogger(CSP.class.getName()).log(Level.SEVERE, null, ex);
         }
           
         
          System.out.println(oid.getText());
        System.out.println(sigs.getText());
       // String qy="update access set OID='"+oid.getText()+"' and Signature='"+sigs.getText()+"' where UID='"+id.getText()+"' and filename='"+fname.getText()+"'   ";
        String qy="update access set OID='"+oid.getText()+"'  where UID='"+id.getText()+"' and filename='"+fname.getText()+"' ";
          //String qy="insert into access(OID,Signature) values('"+oid.getText()+"','"+sigs.getText()+"')where UID='"+signin.uid+"' ";
         try {
             st.executeUpdate(qy);
             //JOptionPane.showMessageDialog(null, "Updated Access Permission to USer");
              
             // this.hide();
         } catch (SQLException ex) {
             Logger.getLogger(CSP.class.getName()).log(Level.SEVERE, null, ex);
         } 
             
           
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          String qy="update access set  Signature='"+sigs.getText()+"'   where UID='"+id.getText()+"' and filename='"+fname.getText()+"' ";
          //String qy="insert into access(OID,Signature) values('"+oid.getText()+"','"+sigs.getText()+"')where UID='"+signin.uid+"' ";
         try {
             st.executeUpdate(qy);
             //JOptionPane.showMessageDialog(null, "Updated Access Permission to USer");
              JOptionPane.showMessageDialog(null, "Send Access Permission to USer");
              this.hide();
         } catch (SQLException ex) {
             Logger.getLogger(CSP.class.getName()).log(Level.SEVERE, null, ex);
         } 
        
         
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CSP().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CSP.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(CSP.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fname;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField name;
    private javax.swing.JTextField oid;
    private javax.swing.JTextField sigs;
    // End of variables declaration//GEN-END:variables
}
