/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package privacy;

import java.math.BigInteger;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EGC
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
     Statement st;
    Connection con;
  int flag=0;
    public signup() throws SQLException, ClassNotFoundException {
        initComponents();
         DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd ");
        Date date = new Date();
        System.out.println(dateFormat.format(date)); //2016/11/16 12:08:43
       dates.setText(dateFormat.format(date));
       
       
       
        
            Class.forName("com.mysql.jdbc.Driver");
       
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"privacy","root","root");
             System.out.println("Connected");
             st=con.createStatement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dates = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        signature = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Efficient Privacy-Aware Authentication Scheme for Mobile Cloud Computing Services");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 890, 40);

        jLabel6.setFont(new java.awt.Font("French Script MT", 3, 24)); // NOI18N
        jLabel6.setText("Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(760, 80, 60, 30);
        jPanel1.add(dates);
        dates.setBounds(839, 80, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Ragavi\\images\\allocation\\sd1.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 200, 190, 210);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("French Script MT", 3, 24)); // NOI18N
        jLabel3.setText("ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 40, 51, 28);

        jLabel4.setFont(new java.awt.Font("French Script MT", 3, 24)); // NOI18N
        jLabel4.setText("Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 90, 67, 28);

        jLabel5.setFont(new java.awt.Font("French Script MT", 3, 24)); // NOI18N
        jLabel5.setText("Age");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 140, 50, 28);

        jLabel8.setFont(new java.awt.Font("French Script MT", 3, 24)); // NOI18N
        jLabel8.setText("Email ID");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 190, 97, 28);

        jLabel9.setFont(new java.awt.Font("French Script MT", 3, 24)); // NOI18N
        jLabel9.setText("Mobile Number");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 240, 147, 28);

        jLabel10.setFont(new java.awt.Font("French Script MT", 3, 24)); // NOI18N
        jLabel10.setText("Signature");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 290, 89, 28);

        jLabel11.setFont(new java.awt.Font("French Script MT", 3, 24)); // NOI18N
        jLabel11.setText("Password");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 340, 100, 28);
        jPanel2.add(id);
        id.setBounds(200, 30, 160, 30);
        jPanel2.add(name);
        name.setBounds(200, 90, 160, 30);
        jPanel2.add(age);
        age.setBounds(200, 140, 160, 30);
        jPanel2.add(email);
        email.setBounds(200, 190, 160, 30);
        jPanel2.add(mobile);
        mobile.setBounds(200, 240, 160, 30);
        jPanel2.add(signature);
        signature.setBounds(200, 290, 160, 30);
        jPanel2.add(pass);
        pass.setBounds(200, 340, 160, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(240, 90, 490, 430);

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Ragavi\\images\\submit.png")); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(740, 330, 200, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
         System.out.println("Store ");
        if(id.equals("") || name.equals("")||age.equals("")|| email.equals("")||mobile.equals("")||signature.equals("")||pass.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Fill All Fields");
            flag=1;
        }
        if(flag==0)
        {
              String sql="insert into registration(ID,Name,Age,Email,Mobile,Signature,Password) values('"+id.getText()+"','"+name.getText()+"','"+age.getText()+"','"+email.getText()+"','"+mobile.getText()+"','"+signature.getText()+"','"+pass.getText()+"')";
      
             try {
                 st.executeUpdate(sql);
             } catch (SQLException ex) {
                 Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
             }
             JOptionPane.showMessageDialog(this,"Registered Successfully");
             try {
                 new SCG().setVisible(true);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        else
        {
           JOptionPane.showMessageDialog(this,"Please Fill All Fields");
       
        }
       
        
         
        
    }//GEN-LAST:event_jLabel12MouseClicked

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    try {
                        new signup().setVisible(true);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField dates;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField signature;
    // End of variables declaration//GEN-END:variables
}
